apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyserver
spec:
  selector:
    matchLabels:
      app: pyserver
  replicas: 1
  template:
    metadata:
      labels:
        app: pyserver
    spec:
      containers:
        - name: pyserver
          image: localhost:5000/pyserver:0.1
          resources:
            limits:
              cpu: 0.5
            requests:
              cpu: 0.5
---
kind: Service
apiVersion: v1
metadata:
  name: pyserver
spec:
  selector:
    app: pyserver
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pyserver-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pyserver
                port:
                  number: 8080
---
